import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import NavBar from '@/components/navbar/navbar'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
    <html lang="pt-br" className='h-full'>
       <body className={inter.className}>
        <main className='relative flex flex-col min-h-screen'>
      <NavBar/>
        {children}
         </main>
        </body>
     
    </html>
    </SessionProvider>
  )
}
